### ISSUE TITLE
Adding traffic light to horizontal roads

### ISSUE THREAD

**Issue by CheriePun** [ocadotechnology/codeforlife-design#101]
Traffic lights snaps to the line between two grids in the vertical direction, but it does not snap to the line between two grids in horizontal direction. The traffic lights that are not snapped to a line will be not be added to the map so it will not be seen in the level when being played.

![screenshot from 2015-06-23 11 12 57](https://cloud.githubusercontent.com/assets/11837539/8303869/09f29cd2-1999-11e5-99bb-d0fe8c09a840.png)
--------

This feature exists already, but it is not clear to the user. Therefore we would like to add into the design some text explaining that you can rotate objects by double clicking on any object.

Please use Figma to design and demonstrate this in a prototype.

Copy requirements: _Here you can liven up your level by choosing the theme and adding scenery! To rotate the objects, double click on them. Will you create beautiful countryside or a bustling city?_

**Comment by lauracumming** [comment]
Stale
