### ISSUE TITLE
Play / go / arrows confusion on game screen

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/codeforlife-design#103]
New users often tend to start with direct drive (arrows and go) and it takes them a while to figure out you can even drag blockly.
Even though "clear" command is useful for direct drive, it's in the menu, far away from arrows.
Users eventually figure out dragging blockly but keep clicking "Go" (as opposed to "Play").
Two ways of starting the execution (play / go) and creating the program (direct drive, dragging blockly) can be confusing.

Possible solutions:
- Having first couple levels only have direct drive and no blockly toolbox or play, step and stop, and the next ones would not have direct drive
- Moving "Play" and possibly "Step", "Stop" and "Clear" to the map ("Play" replacing "Go")  
- Making "Play" more prominent (see ocadotechnology/rapid-router#465).
- Eliminate direct drive completely from all levels
- Eliminate "Go" button

**Comment by lauracumming** [comment]
Stale
