### ISSUE TITLE
Onboarding Complete page doesn't have Kurono copy

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/codeforlife-design#118]
**Describe the bug**
Kurono copy is missing in the benefits section of the page that's displayed upon completing onboarding, only Rapid Router.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.codeforlife.education/
2. Register as a teacher
3. Follow onboarding process

**Expected behaviour**
Benefits section should be updated to include Kurono, too.

**Screenshots**
![Screenshot 2020-01-07 at 12.54.04.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/0cc5ca39-1031-4ade-bb1c-b3c32e16b3c0)

**Comment by lauracumming** [comment]
closing as they will be directed to their dashboard instead now
