### ISSUE TITLE
Hypothesis - Reset code button

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#19]
We believe that adding a way to reset the code would allow students to recover from their mistakes and try again more quickly.

- [x] Define hypothesis

- [x] Define how and what to measure

- [x] Build Prototype

- [ ] Test Prototype

- [ ] Analyse Results

**Comment by mrniket** [comment]
Prototype is built on aimmo repository on branch `reset_code_button`
