### ISSUE TITLE
Unclear how to zoom in Kurono

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#24]
Feedback from two testing sessions highlights this

**Comment by lauracumming** [comment]
Cursor changes to 'pan icon' when over map

Zoom buttons added for temporary fix.

**Comment by lauracumming** [comment]
If we could estimate time and decide whether to implement for 17th please.

**Comment by mrniket** [comment]
Not a priority for now, will close and reopen at a later date if necessary
