### ISSUE TITLE
Complete Python introductory session

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#258]
- [x] Test and complete introduction to Python with CS in Schools
- [x] Research teacher package - what is supplied
- [ ] Pros and cons to approach
- [ ] List out features that we are missing with regards to teacher support over both games

**Comment by lauracumming** [comment]
Can you share link to your notes @rdcruzCFL ?

**Comment by rdcruzCFL** [comment]
@lauracumming  Sorry, I had shared them on Slack 
https://docs.google.com/document/d/1lOpDC1jBHKO0oLIh5soC3sS_LUrzv3aem8LFsFT8gA4/edit#heading=h.ig08lido7obf
