### ISSUE TITLE
No clear success or failure criteria for Kurono challenges

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/codeforlife-design#26]
## The Problem

Students do not know whether their code correctly completes the tasks in the student challenges other than by observing how their avatar moves. Additionally, they do not know the quality of their solution if it's correct or if it's incorrect, feedback on where they went wrong.

**Comment by lauracumming** [comment]
https://docs.google.com/document/d/1o0fGpk9tB_3b2X5bhuBmBYUxUO8MBJ4PiN1piYIzvFM/edit
