### ISSUE TITLE
Product screen recording

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#262]
Record a 1 minute screen recording demonstration of how to find/use Rapid router resources. 
Also provide voice recording using phone.

- [ ] Create a screen recording that is product demo based
- [ ] Get content approved by comms

**Comment by darcie-gomer** [comment]
Demo completed and uploaded to google drive [here](https://drive.google.com/file/d/1nMfjNXSjwQrGiNjldH2HdtCuK1WndT1L/view?usp=drive_link) - still needs approval from comms

**Comment by darcie-gomer** [comment]
Demo approved but needs to be cropped to remove URL and the branding added to the start and end. We need to clarify at governance whether Ocado Tech branding is needed

**Comment by lauracumming** [comment]
Branding clarified. Group for product, teaching materials and general publicity.
OT on careers and STEM events

**Comment by darcie-gomer** [comment]
[Final demo](https://drive.google.com/file/d/1JvO_evB0OD9eTa92zEkXCIcy37jE8DtX/view?usp=drive_link)
