### ISSUE TITLE
Add buttons to resources and videos explaining the lesson

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#294]
This will be viewable when logged in as a teacher.

Base designs on user feedback.

**Comment by lauracumming** [comment]
View for levels when accordion is closed<img width="569" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d666d37a5ba07e33e3dcd044b950602a9dc6167/Python%20Den%20page%20with%20buttons%20closed.png" alt="Python Den page with buttons closed.png" />

**Comment by lauracumming** [comment]
When open for teacher<img width="435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOStlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a7526db44ec68cc40836fbe7dd3ec4bfe6c90d2/Python%20Den%20page%20with%20buttons%20open%20-%20teacher%20view.png" alt="Python Den page with buttons open - teacher view.png" />

**Comment by lauracumming** [comment]
when open for student[Uploading... Python Den page with buttons open - Independent student view.png]

**Comment by lauracumming** [comment]
For independent students, we should show the video links, but for class students, I think the teacher would rather hide them and have the ability to show the video from teh resources if they want to.

**Comment by faucomte97** [comment]
Slightly confused about the levels order etc. I remember you saying that the Den will introduce the split screen instead of the main RR game now, but the first level that does that in RR isn't the first level in the Den here.

Probably easier to talk about this on a call.

**Comment by faucomte97** [comment]
Slightly confused about the levels order etc. I remember you saying that the Den will introduce the split screen instead of the main RR game now, but the first level that does that in RR isn't the first level in the Den here.

Probably easier to talk about this on a call.

**Comment by faucomte97** [comment]
LGTM :)

**Comment by lauracumming** [comment]
Updated colourways[Uploading... Python Den page with buttons closed.png]
