### ISSUE TITLE
Reset password forms

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#299]
There is an inconsistency on the form layout for password rest for teacher and for a student in a class. 
Also, if the user resets the password with one that doesn't fit the criteria, the warning is displayed in red, but the page reloads on submission of the new data and takes the user to the top of the page. This means that as a teacher, you may think you have reset a student password successfully when you have not. 

![Screenshot 2023-07-26 at 12.31.09.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/02c47555-8ed6-46ac-93de-52d1af809e07)![Screenshot 2023-07-26 at 12.31.43.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/8ef774ce-5418-416b-8310-5a607f5954e5)

We need to make the design consistent across both users and ensure that the user is made aware if the password met or didn't meet the criteria needed: 'weak/common' error doesn't show as user types, only after submission. We need to make user it shows as it does on the other forms to inform the user before submission.

**Comment by faucomte97** [comment]
Fixed in the new system.
