### ISSUE TITLE
Add Gmail button to verify email page

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#320]
There is a large percentage of users that are not verifying their accounts and we are not sure why.
We would like to try and improve the percentage of teachers and Independents that verify their accounts by adding in a link that takes them directly to the email in their inbox.

- [ ] Investigate best practice
- [x] Add a button in Figma

**Comment by lauracumming** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3dqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c766d7ca818c6af336caf560817fa43dfd503da/Screenshot%202023-10-11%20at%2009.21.18.png)

**Comment by lauracumming** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dafd0fde4ef5a6cdeafdf0773b85ee87772215cb/Screenshot%202023-10-11%20at%2019.48.33.png)

**Comment by lauracumming** [comment]
We think this is possible, but i'd like to investigate a bit more before handing to dev.

**Comment by SKairinos** [comment]
Here is an example of a link where you can filter your inbox to all emails I sent you:
https://mail.google.com/mail/#search/from%3A+stefan.kairinos%40ocado.com
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27d3133331fb55d2509d7346291728f847ea24c1/image.png)

**Comment by SKairinos** [comment]
We can also additional filters. Like searching for subjects including a key phrase.
https://mail.google.com/mail/#search/from%3A+stefan.kairinos%40ocado.com+subject%3A+infrastructure
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW1CQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ee42a672b9b9f73ba9350bbea8576f782be15f5/image.png)
