### ISSUE TITLE
Create user (teachers) test for Kurono worksheets

### ISSUE THREAD

**Issue by darcie-gomer** [ocadotechnology/codeforlife-design#327]
- [ ] Recruit
- [x] Write question guide
- [ ] Build test
- [ ] Note taking template
[Discussion guide doc](https://docs.google.com/document/d/1nSWv6NuQRneQFXc5t60h5cLfn8raAhtixR2iHsJS0Ac/edit?usp=sharing)

**Comment by lauracumming** [comment]
Maybe this moves to following sprint after recruitment?
