### ISSUE TITLE
Update contact list for schools

### ISSUE THREAD

**Issue by darcie-gomer** [ocadotechnology/codeforlife-design#328]

**Comment by darcie-gomer** [comment]
[Contact list](https://docs.google.com/spreadsheets/d/1ydb2jT4dEa-DpNrT3GrDrgMln9Zom-S-TkHx51pejds/edit?usp=sharing) - 'Permissions request tracker' sheet now has all names/emails that we need to contact to ask if we can keep their data stored

**Comment by lauracumming** [comment]
Convert to address book in Dotdigital

**Comment by lauracumming** [comment]
See if we can automate the opt in through Dotdigital
