### ISSUE TITLE
Design COVID-19 landing page

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/codeforlife-design#34]

**Comment by lauracumming** [comment]
This is waiting on the guides form Rebecca. Otherwise ready.

**Comment by lauracumming** [comment]
updated with new copy

**Comment by lauracumming** [comment]
@mrniket 

Mouseflow funnel set up to follow users from Home page to Parent page to Registration
Google analytics set up to also follow also and to track level 1 plays of Rapid Router to see if we get:

1. Increase in traffic to RR level 1
2. Increase in traffic to Independent sign up
3. Increase in traffic to Home Learning page
