### ISSUE TITLE
Process all Kurono data from Lyssna to atomic board

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#371]
We need to consolidate all of our data we have collected on Kurono usage and process it to the atomic research board. 
The idea is to create snippets of knowledge with links to forms or videos etc.

If time, also process any Kurono data from the folders to add to this. 
If no time, create an additional card to do this in next sprint.

**Comment by darcie-gomer** [comment]
Miro board frame created in the Atomic Research Board: https://miro.com/app/board/uXjVOqtXNnk=/?moveToWidget=3458764573320501575&cot=14
