### ISSUE TITLE
Research where teachers expect to find the resources links 

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#377]
We would like to get some feedback around the links to resources and navigation.

We have some designs to test reactions and we can dig further to see if this would be a useful place for them or if they have other ideas. This will be online testing.

- [x] Research plan
- [x] Research method
- [ ] Send out

**Comment by darcie-gomer** [comment]
[Research Plan](https://docs.google.com/document/d/16onsCiixEsuByBfg5D1kQRMHRImQXVmjcV32C9IvVSc/edit)
[Dotdigital email draft](https://r1-app.dotdigital.com/Campaigns/Step/EasyEditor.aspx?id=1512608&campaigntype=unsent)
[Test draft on Lyssna](https://app.lyssna.com/tests/5fb66f5b5e46/edit)

**Comment by darcie-gomer** [comment]
[Test finalised on Lyssna](https://app.lyssna.com/sets/df413a) - need comms approval on email and socials post

**Comment by darcie-gomer** [comment]
Comms have approved the [email](https://r1-app.dotdigital.com/Campaigns/Step/SelectContacts.aspx?id=1512608) and the [tweet ](https://docs.google.com/spreadsheets/d/1lmeGfPjQJwnkrUZ-217eQEUlkizcSU6PPFH_Jxljewo/edit#gid=0), they now just need to be scheduled and sent/posted
