### ISSUE TITLE
Pull out data from RR interview

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#380]
We would like to add some nuggets of insight from our Rapid Router interview recently, in order to discover if we have any existing data that marries and also if there is any lurking at the back of Laura's memory that needs extracting.

- [ ] Process to repository as 'nuggets' (add links to anything relevant like mentioned competitors, Quotes, stats and statements - basically anything we feel is important).

**Comment by darcie-gomer** [comment]
Created [this frame](https://miro.com/app/board/uXjVOqtXNnk=/?moveToWidget=3458764574390749889&cot=14) in the atomic research board to summarise the interview
