### ISSUE TITLE
Create user journeys for Kurono testing

### ISSUE THREAD

**Issue by darcie-gomer** [ocadotechnology/codeforlife-design#385]
St Benedicts:
- [ ] Worksheets 1 & 2 class
- [ ] Worksheets 3 & 4 class

Dame Alice Owens:
- [ ] Coding club
- [ ] Worksheets 1& 2 class

STAGS
- [ ] Worksheets 1 & 2 class
- [ ] Worksheets 3 & 4 class

**Comment by lauracumming** [comment]
Stale
