### ISSUE TITLE
Agree and book in testing with two teachers for IDE

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#393]
We would like to test the IDE resources with teachers to gain feedback and improve before release later in the year.

- [x] Agree method and arrange timings with two teachers

**Comment by darcie-gomer** [comment]
[Notes from our kick off sessions with teachers](https://docs.google.com/spreadsheets/d/10jiDvkn4SP6gZYi57SamxAyjoHm1OxB-uBi3HDxtRlo/edit?usp=sharing)
