### ISSUE TITLE
Revisit definition of goals/vision for Kurono and Rapid Router

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#4]
@lauracumming commented on [Mon Oct 28 2019](https://github.com/ocadotechnology/codeforlife-admin/issues/75)

I'd like to have a session with the team where we go through the purpose, our audience and goals etc to realign our vision and ensure that I am aligned to the business and team.

**Comment by darcie-gomer** [comment]
Combined with ticket #995
