### ISSUE TITLE
New Python module -  interview/set up

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#402]
We need to prep and book in calls with the people that are testing the IDE resources. This will only be for a couple, as we will then turn to unmoderated research.

We will need to get everybody else set up though and keep a record so we know who is part of the cohort.

**Comment by darcie-gomer** [comment]
[Research plan](https://docs.google.com/document/d/1TQUN6CoDuOssw9y1wJKxCIAkfJTFEpjnQ7iLHaf1iuQ/edit)
[Interview discussion guide](https://docs.google.com/document/d/1jy0WHWmZ2CGWoUqy66mPH7p9Tz8BWYWjQJk2rbTgxH0/edit)

**Comment by darcie-gomer** [comment]
[Survey guide]([url](https://docs.google.com/document/d/1x3o8D7N5oj78friI0bfLUr424e5-ndcQENlwTVMgFDw/edit))
No longer running interviews (apart from possibly with one teacher and the Ocado independent learner)
