### ISSUE TITLE
Getting started with Rapid Router (no.5 of 10)

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#408]
Video walkthrough for teachers (getting started with Rapid Router)
How to create a school, class and how to monitor student progress too.

**Comment by lauracumming** [comment]
Ready for review please:https://drive.google.com/file/d/1Y2J_cSBAEKcQrJOB2b_TkRy8MNsthL61/view?usp=drive_link

**Comment by lauracumming** [comment]
No, it's not. One moment please...

**Comment by lauracumming** [comment]
Okay, try again: https://drive.google.com/file/d/1Y5C5am6hwAeRoJVYCgUSna2y6lqdcaWO/view?usp=drive_link

**Comment by lauracumming** [comment]
@faucomte97 please check

**Comment by faucomte97** [comment]
@lauracumming all good 👍🏻
