### ISSUE TITLE
Find copyright free sound for electric van

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#413]
We would like to find some alternative copyright free sounds that we can use for the van start up. We are happy to acknowledge the use.

- [x] Electric vehicle start up
- [ ] Santa sleigh start up (Reindeer noise?)

**Comment by andrewmales** [comment]
Could we ask someone in an Ocado spoke to just record an electric van starting up?
(I haven't got Santa's number for the other one, though. :) )

**Comment by evemartin** [comment]
Here are some sound options from Pixabay (content license [here](https://pixabay.com/service/license-summary/))! If we go with any of these we will have to cut the audio to the right length.

More realistic: [Car Engine](https://pixabay.com/sound-effects/carengine-5998/) or [Electric Desk Fan Turning On and Off](https://pixabay.com/sound-effects/electric-desk-fan-turning-on-and-off-121339/)

More sci-fi: [Cartoon Drive Car Game Sound](https://pixabay.com/sound-effects/cartoon-drive-car-game-sound-38094/), [Laser 03](https://pixabay.com/sound-effects/laser-03-39231/), or [Simple Zaps](https://pixabay.com/sound-effects/simple-zaps-48107/)

**Comment by evemartin** [comment]
For Santa's sleigh, here are some bell sound effects that I think sound pretty Christmassy:

[Jingle Bells](https://pixabay.com/sound-effects/jingle-bells-107671/), [Sleigh Bells Shaking](https://pixabay.com/sound-effects/sleigh-bells-shaking-67086/), [Sleigh Bells](https://pixabay.com/sound-effects/sleigh-bells-7-22-12-edit-99843/)

Plus a bonus [Ho Ho Ho](https://pixabay.com/sound-effects/ho-ho-ho-merry-christmas-santa-claus-181123/)

**Comment by lauracumming** [comment]
The fan works well for an electric car - good find!!!

**Comment by ligiaolmos** [comment]
Agree! Fan sounds more smooth like an electric engine :)

**Comment by lauracumming** [comment]
Let's use the fan for the car, and the ho ho ho for when the sleigh crashes. Do we have bells on the sleigh at the moment for starting? If not, let's use the sleigh bells for that.

**Comment by faucomte97** [comment]
Don't think we do

**Comment by faucomte97** [comment]
FYI: The dev task for the Christmas sounds: https://github.com/ocadotechnology/rapid-router/issues/1556
