### ISSUE TITLE
Design wind turbines (can they be animated?)

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#415]
In order to add some variation to our Rapid Router levels, we would like to create some new elements based on the environment. This task is looking at wind turbines and creating the graphics that need to sit on the maps. 

You should be able to add these in the level creator too. Take a look in the level editor to understand how they could work with other elements: https://www.codeforlife.education/rapidrouter/level_editor/#

Use either Illustrator or Figma to create your working and SVG files.

Note: We have a Desktop first approach as most users are on Desktop.

**Comment by ligiaolmos** [comment]
Hi @lauracumming I can see the issue but am not sure how to assign it to myself. Feel free to assign it to me.

**Comment by ligiaolmos** [comment]
Hi @lauracumming I hope you're doing well. I've been working on a draft for the wind turbines, and before proceeding further, I'd like to confirm with you about the direction I'm taking in terms of style. I reviewed the game assets and noticed a very cartoonish aesthetic, so to maintain consistency, I've sketched two different wind turbines that I hope match the game's style. I've attached them here and would like to clarify a few points:

Between Wind Turbines version 1 and 2, which one do you prefer?
Regarding the view (positioning/perspective), can we adopt a similar perspective as that of the traffic lights?
I've experimented with three different color palettes. What are your thoughts on them?
There's still some polishing needed, but I'd love to hear your thoughts before proceeding further.

Thanks!
Ligia
![Test_in_game](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/3d17ae91-39d2-4e46-8c5b-1a6c9784c775)
![WindTurbines_RapidRouter_1](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/14f7883f-5d76-44eb-9901-7259c0235201)
![WindTurbines_RapidRouter_2](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/4e9a9e13-b364-4014-a2f8-baaf0d51bfae)

**Comment by ligiaolmos** [comment]
Hi @lauracumming following our discussion on Slack I gave a try on drafting the wind turbine from above.. it looks pretty weird. I will work on a draft for the solar pannels that will probably work better on that perspective 
![Uploading Screenshot 2024-03-28 at 11.22.00.png…]()

**Comment by ligiaolmos** [comment]
Here is the Solar Panel sketches @lauracumming. Let me know what you think. Thanks
![Solar_Panel_RapidRouter](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/625db6f4-e6db-4621-a0e0-bfad00d42dc0)

**Comment by ligiaolmos** [comment]
Hi, I added the final asset to g.drive link here: https://drive.google.com/drive/folders/1eSLlduZOpHdBaV7Q6GnNT3-hHvqggy25?usp=drive_link
![Solar_Panel](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/a42c7e72-8b57-4a4e-a458-d3fa84b93afb)
