### ISSUE TITLE
Electric Van for Rapid Router

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#419]
In order to give users the opportunity to create an environmentally friendly map, we are introducing new 'green' elements to Rapid Router. We would like to create a new version of the van that is electric so that users have a choice of van alongside the characters. 

- [x] Create version of Rapid router van (no logo) that represents electric van
- [ ] Save as SVG and PNG

**Comment by ligiaolmos** [comment]
![Electric_Van-01](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/99f5815a-cf37-4cf6-944b-b0c25d684301)
![Electric_Van-03](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/6d13eee3-9bc2-4b6d-bab6-21d41cfc0841)
Hi @lauracumming I sketched some options for the electric van and tested a couple of colour combos. What do you think?

**Comment by lauracumming** [comment]
These are great @ligiaolmos. Do the files allow you to remove that inner rectangle on the back of the van? It would be good to get the symbols a bit bigger so that when reduced down in size they are more visible.

**Comment by ligiaolmos** [comment]
Hi @lauracumming sure! Here it is with the sign bigger. Which version
![Uploading Electric_Van.png…]()
 do you think could work best?

**Comment by lauracumming** [comment]
These are great. We like the bolt on the blue (version 1) - could we still go bigger though and make it stand out more?
We also like the circular plug (version 2) and feel that this may give off more of an renewable energy approach. We like the van body in the blue and the van front in the grey. Please could we see these two again with the changes described?

**Comment by ligiaolmos** [comment]
![Screenshot 2024-04-16 at 15 03 40](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/381bb782-13be-45c5-abf9-4eba9d0e89e3)
![Screenshot 2024-04-16 at 15 03 49](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/afb4f91c-8407-4ed4-9a05-98cea60050ae)
![Screenshot 2024-04-16 at 15 03 58](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/525e47ff-ae5a-4876-bca7-61392bb9821f)
Hi @lauracumming here it is with the changes and tested within the gameplay. Wdyt?

**Comment by lauracumming** [comment]
Version A please @ligiaolmos

**Comment by ligiaolmos** [comment]
![Electric_Van](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/9653abce-2fce-4a89-bb58-a18d685aea28)
![Electric_Van](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/12f17cf8-9b2d-4041-bf14-13667d10a31c)
Hi @lauracumming I'm adding here the assets in PNG and SVG format, also uploaded them to GDrive [here](https://drive.google.com/drive/folders/1iLpUvurTeCoh_Ut8lo3-Z-EuvyW6PMAk?usp=drive_link). Let me know if I can help with anything else. Thanks!

**Comment by lauracumming** [comment]
Great. Thank @ligiaolmos superstar!
