### ISSUE TITLE
Update contribute page on website

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#420]

**Comment by lauracumming** [comment]
@SKairinos , can you take a look at the page update and see if we want to add in any direct links to set up etc?
https://www.figma.com/file/9pMg7hFzK5YkjcnmwZsFl1/Portal-UI?type=design&node-id=108%3A7193&mode=design&t=ZTomggiZCESqFiFo-1

**Comment by SKairinos** [comment]
I would add this link to [setup your dev environment ](https://docs.codeforlife.education/git/common-setup-1)

should we link it directly in the site or on [this page in git-book](https://docs.codeforlife.education/developer-guide/contributing-as-developer)?
