### ISSUE TITLE
Under 13 Independent user - verify email page

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#422]
We would like to present a more age appropriate verify email page for under 13's.

As a child, I would like to understand that my parent needs to verify the account I just created using their email address so that I can bug them to do it.

Amend existing design to be more age appropriate. Remove buttons - as the child will be asking the parent to do it for them.

Create the design in Figma Portal.

<img width="1304" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0JZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97650795cfb5b3642f54766293e0719f809d585e/Screenshot%202024-04-12%20at%2016.27.25.png" alt="Screenshot 2024-04-12 at 16.27.25.png" />

**Comment by faucomte97** [comment]
@lauracumming You mention needing to create a design in Figma for this, is this still the case?

**Comment by faucomte97** [comment]
LGTM
