### ISSUE TITLE
Cover graphics for slide and hero image

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#426]
We would like to create some hero images using the new Python Den branding.

- [x] Cover slide for slide decks 
- [x] Hero image for website pages (banner - 1980 x 320)
- [x] Hero image for Gitbook lesson plan (1216 x 293)
- [x] Hero image for website (555 x 410)

Existing examples below.

<img width="1894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU4yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16757aeb311d9b3838ada4cfe886dbb1382cb207/Screenshot%202024-06-19%20at%2011.24.12.png" alt="Screenshot 2024-06-19 at 11.24.12.png" />
<img width="1094" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVIyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dc40a1896ef384c0a816ff381cdbce8a2d816c7/Screenshot%202024-06-19%20at%2011.23.36.png" alt="Screenshot 2024-06-19 at 11.23.36.png" />

Please save to folder once completed: https://drive.google.com/drive/folders/1CPC5q_lT-G6qhCriFcznemtz0ChkZQOB?usp=drive_link

**Comment by lauracumming** [comment]
Website banner<img width="1980" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1crQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1868c15f2d44d3239532cb338b4a5aaff2a92f6/Python_Den_hero_web.png" alt="Python_Den_hero_web.png" />

**Comment by lauracumming** [comment]
Gitbook<img width="1216" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0cvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a762a35b9a9f120306b6a778f7b01cc7966f6c2b/Python_Den_hero_gitbook.png" alt="Python_Den_hero_gitbook.png" />

**Comment by lauracumming** [comment]
/teach page marketing image<img width="555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeksvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ed4793cf8fb154cf890e8fd8573dca3718580fc/Marketing%20image%20for%20website%20%281%29.png" alt="Marketing image for website (1).png" />

**Comment by lauracumming** [comment]
Ready for review.

**Comment by faucomte97** [comment]
LGTM
