### ISSUE TITLE
Artwork merch

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#429]
- [x]  pencils
- [x]  stickers
- [x]  table cloth
- [x]  10 yr tees (for quote)

**Comment by lauracumming** [comment]
<img width="326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODRBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4984da7833ea1aa1dc9c6168f11989fddacad86f/Screenshot%202024-05-22%20at%2013.35.29.png" alt="Screenshot 2024-05-22 at 13.35.29.png" />

**Comment by lauracumming** [comment]
<img width="590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4ec4d1fb7a59487e8842bb248146aeae967b97a/Screenshot%202024-05-22%20at%2013.37.18.png" alt="Screenshot 2024-05-22 at 13.37.18.png" />

**Comment by lauracumming** [comment]
<img width="1354" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--690308f7b6b3929ce5730aa7102938cc2f37a4a7/Screenshot%202024-05-22%20at%2013.38.12.png" alt="Screenshot 2024-05-22 at 13.38.12.png" />

**Comment by lauracumming** [comment]
Do you think we should go for a)[Uploading... Screenshot 2024-05-22 at 16.20.11.png]
or

**Comment by lauracumming** [comment]
b)<img width="333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ecaf584716fbcbfb95fbc43bbcb0fa684cacd3d9/Screenshot%202024-05-22%20at%2016.19.57.png" alt="Screenshot 2024-05-22 at 16.19.57.png" />

**Comment by lauracumming** [comment]
Notice the cutter guides - do you have a preference if it hugs the number or not?

**Comment by faucomte97** [comment]
A is nicer I'd say

**Comment by lauracumming** [comment]
These have been sent to the printer for review

**Comment by lauracumming** [comment]
Sent to printer
