### ISSUE TITLE
Create alternative graphics (snow and city) for solar panels

### ISSUE THREAD

**Issue by evemartin** [ocadotechnology/codeforlife-design#433]
We need to create snowy graphics for the solar panels so that we can use them as scenery in the Snow theme and during the Christmas holiday period, as well as a graphic of a house with solar panels to be used in the City theme.

Standard solar panel graphics can be found here: https://drive.google.com/drive/folders/1eSLlduZOpHdBaV7Q6GnNT3-hHvqggy25

- [ ] snowy solar panel graphic created
- [ ] house with solar panels graphic created

**Comment by Beekeeper787878** [comment]
I can start on this task soon

**Comment by EnoraHauduc** [comment]
Here are screenshots of the solar panels. 
<img width="297" alt="image" src="https://github.com/user-attachments/assets/160fd021-0507-4cad-bb78-76bf076a7d34">
<img width="212" alt="image" src="https://github.com/user-attachments/assets/41990228-9833-42f4-960d-7acb28ae583f">
<img width="346" alt="image" src="https://github.com/user-attachments/assets/7e9f3f8f-6cc9-4343-b509-e72ef1b5bd5b">
<img width="308" alt="image" src="https://github.com/user-attachments/assets/e66b746b-7b13-40ec-900c-884ff66347e7">

**Comment by lauracumming** [comment]
Solar panels on the house looks good - let's just have them on one side though please. Keep the double version.

**Comment by EnoraHauduc** [comment]
Yes, of course. I can remove the solar panel on the smaller part of the house if you'd like?

**Comment by EnoraHauduc** [comment]
Is this better? 
<img width="503" alt="image" src="https://github.com/user-attachments/assets/3962a703-30e0-4f91-9565-7bef9f730be0">

**Comment by lauracumming** [comment]
Snow looking good too. Remember though to have shadow and light on opposite sides. 🙂

**Comment by EnoraHauduc** [comment]
Of course, I will fix that tomorrow

**Comment by lauracumming** [comment]
Looks great! 👍

**Comment by lauracumming** [comment]
Yes, better, but remember, the shadows and highlights should follow the curve of the snow. Imagine it bumpy.
You wouldn't have a highlight crossing a crevice. 
![Screenshot 2024-08-02 at 10 22 59](https://github.com/user-attachments/assets/dd8edec5-3c13-4add-a0e9-fb2de2437e16)
![Screenshot 2024-08-02 at 10 22 55](https://github.com/user-attachments/assets/e7d23b65-544a-42b6-8410-8f76ceea9494)

**Comment by EnoraHauduc** [comment]
Is this better? 
<img width="470" alt="image" src="https://github.com/user-attachments/assets/c787138e-4f68-480e-963d-e9ad43cff81a">

**Comment by lauracumming** [comment]
Yep! That works!
