### ISSUE TITLE
Design Python Den levels page

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#435]
**Summary**
We would like to create the design for the Python den page. It will be based on the same layout as Rapid Router pages.
A levels page and a game page. The game page will embed the Raspberry Pi IDE. This task is for the levels page only.

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a student
_I would like to visit the Python Den page 
_so that I can start attempting the levels

**What pages will be changed?**
https://www.codeforlife.education/pythonden

**Outcome/deliverable**
A Figma design of the levels page for Python Den.

**Tools**
Figma

**Concerns**
Use new Python Den colours and fonts

**Deadline**
June/July

**Links**
https://www.codeforlife.education/rapidrouter/

**Reviewer**
@lauracumming 

**People to contact**
@lauracumming

**Comment by lauracumming** [comment]
This came into the buttons ticket so is ready for review too - please check other ticket

**Comment by lauracumming** [comment]
https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/codeforlife-design/294

**Comment by faucomte97** [comment]
LGTM :)
