### ISSUE TITLE
Resources pages need to be consistent and easy to navigate

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#44]
Rapid Router resources are heavy and dispersed on the page meaning it is difficult to digest what is available to the user. We need to design a clean way of displaying the links to documents for the different stages that can be applied to both game resource pages.

**Comment by mrniket** [comment]
We need to check how teachers download resources. I.e. whether they download PDFs individually or in sets. This would help us prioritise which option we make more prominent.
