### ISSUE TITLE
Coffee break quiz

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#442]
**Summary**
We would like to start linking 'real world' examples of our code into the teacher/student worksheets to help explain where examples may be used. We would like to understand if teachers would find this useful.

**Outcome/deliverable**
Create a research quiz to understand if there is use for this.

**Tools**
Lyssna

**Deadline**
This sprint

**Reviewer**
@lauracumming 

**People to contact**
@lauracumming

**Comment by lauracumming** [comment]
@faucomte97 please can you provide a simple 'real world' example of our code that demonstrates an if statement and give an explanation of what it does on our website or game.

**Comment by faucomte97** [comment]
<img width="610" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97da24a39da547103da14abadeae766285817add/Screenshot%20from%202024-08-12%2015-23-42.png" alt="Screenshot from 2024-08-12 15-23-42.png" />

<img width="610" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWROQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d09810ba39e843e6e95a6473c998a19feb2ddc5/Screenshot%20from%202024-08-12%2015-37-15.png" alt="Screenshot from 2024-08-12 15-37-15.png" />

**Comment by faucomte97** [comment]
looking at them again the second one is better

**Comment by lauracumming** [comment]
please test: https://app.lyssna.com/preview/989eac55fe71

**Comment by faucomte97** [comment]
LGTM, we can even add that the if statement implements Santa too
