### ISSUE TITLE
Design a city animal for the level editor

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-design#443]
**Summary**
The level editor has cows that you can place on the road (and eventually, just around on the map).
The cows make sense in the Grass, Farm and Snow themes but not so much in the City theme - so we need to replace the cows with another animal for the City theme.

Ideas include: fox, horse, cat, pigeon. Open to other ideas.

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a Rapid Router user creating a level in the level editor_
_I would like to have a different option to the cows in the City theme_
_so that my level makes sense_

**What pages will be changed?**
Level editor page, Scenery tab.

**Outcome/deliverable**
- [ ] Image of a top-down city animal
- [ ] Sound file of the animal's noise (for when the van honks and the animal vanishes).

**Tools**
Image: any software that feels comfortable - we use Illustrator
Sound: https://www.bensound.com/ (not sure if it'll have animal sound effects)

**Concerns**
Sound file must be royalty-free.
Image should ideally be an SVG.

**Links**
https://www.codeforlife.education/rapidrouter/level_editor/#

**Reviewer**
@lauracumming 

**People to contact**
@lauracumming @faucomte97

**Comment by Beekeeper787878** [comment]
I'll pick this task up soon

**Comment by EnoraHauduc** [comment]
<img width="504" alt="image" src="https://github.com/user-attachments/assets/4c014e7a-ad6b-4da8-bd93-2b257388692e">
<img width="417" alt="image" src="https://github.com/user-attachments/assets/c9ba5c03-3e72-4e51-b4f7-ae8f0f5f824d">
Here are the finished pigeons!

**Comment by EnoraHauduc** [comment]
Here is the svg file for the pigeon
![Uploading Patricia Pigeon [Final] copy.svg…]()

**Comment by EnoraHauduc** [comment]
I have found a royalty-free and copyright-free pigeon sound here. The last second or so might need to be trimmed off but I think this is the best one overall that I found. 
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/b074b36c-d271-4238-9696-bde67dc5d27a">
https://cdn.pixabay.com/download/audio/2021/08/04/audio_4d30f93855.mp3?filename=pigeons-flying-6351.mp3

**Comment by lauracumming** [comment]
Great stuff.
