### ISSUE TITLE
Design a grass / pavement path for non-van characters in the City theme

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-design#444]
**Summary**
In Rapid Router's level editor, specific themes can be chosen when creating a level, as well as different characters. When selecting either of the "Van" characters, the road tiles assets are actual road images.
However, when selecting a non-van character, the road automatically changes to a dirt path. While this makes sense within the "Grass", "Farm" and "Snow" themes, it doesn't really make sense within the "City" theme.
You can see an example of that in [level 78](https://www.codeforlife.education/rapidrouter/78/#) where Phil walks around a City on a dirt path.

Having the non-van characters walk on a grass path (or a pavement would probably be even better) would make more sense.

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a user creating a custom level in Rapid Router, with a character who's walking around a city,_ 
_I would like the path to be a pavement instead of a dirt path_ 
_so that my level makes more sense within the City theme_ 

**What pages will be changed?**
Level editor, Rapid Router game page

**Outcome/deliverable**
- [ ] New asset / image of a pavement tile

**Tools**
Illustrator or any preferred image editing software

**Reviewer**
@lauracumming 

**People to contact**
@lauracumming @faucomte97

**Comment by lauracumming** [comment]
I have discovered this tile - please check it in Illustrator and see whether it could be sufficient.

<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0FnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8fc97ef7ff69662d3402093212e308a2ecf9886/pavementTile.svg" alt="pavementTile.svg" />

**Comment by lauracumming** [comment]
Closing as we have
