### ISSUE TITLE
Additional admin reminder for teacher

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#446]
**Summary**
Design Additional admin reminder for teacher - when teacher leaves school - what happens when teacher goes to delete account

**User story**
The user story that has led to the need for this task, expressed in the format below.
_As a_ 
_I would like_ 
_so that_ 

**What pages will be changed?**
What pages, artefacts or areas will be changed? Desktop, app or both? Tip: Be specific as possible to ensure we know the exact part of the software that is to be changed.

**Outcome/deliverable**
What will be the outcome once this task has been completed? What deliverables (code, documents, posts, decks, emails etc) do you expect/need to be produced? What format should they be in? How many designs are you looking for - 1 or several?

**Tools**
What tools would you recommend/stipulate to use?

**Concerns**
Do we need to consider anything such as licences, copyright, colours, platform, fonts, accessibility, file sizes?

**Deadline**
When does the task need to be completed by? Specific or rough date. Tip: Don't just put ASAP!

**Links**
Insert any hyperlinks to sites or documents that may help with this task.

**Reviewer**
Who should review this task?

**People to contact**
List the people that should/could be contacted before/during/after this task is done.

**Comment by lauracumming** [comment]
<img width="1312" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODlqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--937088b8f18796e04dd1259b879a07d32cdb4301/Delete%20account%20-%20classes%20and%20admin.png" alt="Delete account - classes and admin.png" />

Question. If we use the same design pattern to warn teachers about stuff when they delete their accounts we end up with a double. So, I'm thinking we bullet stuff instead like shown below.

**Comment by lauracumming** [comment]
<img width="1312" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ZqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9613d752aadea99e34f4929296de7f1b675c9ac/Delete%20account%20-%20classes%20and%20admin%20V2.png" alt="Delete account - classes and admin V2.png" />

**Comment by lauracumming** [comment]
@faucomte97 - ready for review

**Comment by faucomte97** [comment]
I actually kinda prefer the first design, I find it clearer as to what the user still needs to do to delete their account.

**Comment by faucomte97** [comment]
I actually kinda prefer the first design, I find it clearer as to what the user still needs to do to delete their account.

**Comment by SalmanAsh** [comment]
I also like the first one. Its nice and clear.

**Comment by lauracumming** [comment]
Majority preferred existing pattern, so we will do that with reminder. Dev task to be created before closing.
