### ISSUE TITLE
Marketing video for Python Den

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#447]
We would like a short promo video for the Python Den. 

Two short screen recordings of completing a task would be good:
 
- [ ] one using the text editor
- [ ] one using the new RR levels
 

Then @lauracumming can top and tail them

Add link to recordings here when completed.

**Comment by faucomte97** [comment]
Looks good to me.
Especially the stranger things-y music

**Comment by SKairinos** [comment]
LGTM

**Comment by lauracumming** [comment]
Ready to upload to Portal. Uploaded to Youtube
