### ISSUE TITLE
Update Home learning page to map to Independent resources

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#453]
**Summary**
We need to update the Home learning page on the portal

**User story**

_As a home learner
_I would like to be able to find the correct resources
_so that I can learn as an independent outside the classroom

**What pages will be changed?**
https://www.codeforlife.education/home-learning

**Outcome/deliverable**

- [ ] Updated text on portal
- [ ] Updated link to Gitbook

**Tools**
Figma

**Concerns**
None

**Deadline**
This sprint

**Reviewer**
@SKairinos @faucomte97 

**People to contact**
@lauracumming

**Comment by faucomte97** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM
