### ISSUE TITLE
Artwork panels for Bett show 2025

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#455]
- [x] Prepare exhibition panels for print
- [ ] Sign off
- [ ] Send to GES

**Comment by faucomte97** [comment]
[Ocado_Bett_Show_Panels@25%_2025_OL.pdf](https://github.com/user-attachments/files/17776886/Ocado_Bett_Show_Panels%4025._2025_OL.pdf)

**Comment by faucomte97** [comment]
@lauracumming panels look good, only thing is that the Python Den characters look ever so slightly pixelated.
