### ISSUE TITLE
Artwork for Desk - Bett show

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#456]
- [x] Create artwork for desk
- [x] Get sign off

**Comment by lauracumming** [comment]
[Ocado-GRO5-Desk Counter_PRINT.pdf](https://github.com/user-attachments/files/17893935/Ocado-GRO5-Desk.Counter_PRINT.pdf)

Ready for review

**Comment by lauracumming** [comment]
@duncanrussell-ocado please take a look

**Comment by duncanrussell-ocado** [comment]
Approved. Great design
