### ISSUE TITLE
Design system for portal

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/codeforlife-design#6]
## Task Description
We would like to create a more comprehensive design system for the portal so that it will be easier to work on any future design iterations. Eradicate all unused and unlinked symbols and styles.

## Acceptance Criteria
- Use the AI:MMO design system as a basis
- Use portal colours and fonts
- Update / create more iconography
- Consider animation
- Utilise a customised material design system for interactions

**Comment by lauracumming** [comment]
The system is outdated and needs overhaul

**Comment by mrniket** [comment]
Closed at we are going to do this iteratively instead of a "big bang" release
