### ISSUE TITLE
Review and amend teacher prototype after testing

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#62]
Amend according to testing results

**Comment by lauracumming** [comment]
https://docs.google.com/presentation/d/1gUf-R1Pe6obAsOOJ3Ab2jDQri4I6LRMikEIAS2hzUs8/edit?usp=sharing

**Comment by lauracumming** [comment]
Amends to do from Miro comments

**Comment by mrniket** [comment]
closing as this is part of #15
