### ISSUE TITLE
Educate page

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#77]
The educate page needs a Kurono section adding with a demo. 
Need to link to Kurono.

**Comment by dionizh** [comment]
I think there needs to be link to ‘Teaching Resources’ on the Teacher dashboard (the page that you get when you click the Teacher button). When I browsed for the first time, I kinda expected everything I need as a teacher to be on that page. It took me a while to see the 'Teaching Resources' on the top navigation bar. 

I understand 'Teaching Resources' is only available after logging in. Perhaps the Teacher dashboard/page can be modified to display differently after logging in to include the extra information. I think it's not uncommon for a page to have different content pre and post login.

**Comment by lauracumming** [comment]
Ready for review
