### ISSUE TITLE
Volunteering pages on Portal

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#87]
New volunteering page that explains:

1. CFL Ambassadors
2. Volunteering and contributing to the code base.

**Comment by lauracumming** [comment]
Awaiting rebrand.
https://miro.com/app/board/o9J_l_bctrs=/

**Comment by lauracumming** [comment]
updated - please review

**Comment by faucomte97** [comment]
@lauracumming Looks good :)

**Comment by lauracumming** [comment]
Ready for Dev
