### ISSUE TITLE
Investigate solutions for independent students

### ISSUE THREAD

**Issue by paulheideman** [ocadotechnology/codeforlife-design#98]
Independent students don't have access to the teaching packs, and could get stuck on a level.

We need some criteria so the answer isn't accessible straight away.  Or maybe record the fact that the answer was shown.

**Comment by lauracumming** [comment]
They now have access, but I think this is part of a bigger problem with regards to what we offer Independent students and how we tailor to them.

**Comment by lauracumming** [comment]
Closing to create a new task as they have access now
