### ISSUE TITLE
Add some Python introduction and instructions for independent students

### ISSUE THREAD

**Issue by paulheideman** [ocadotechnology/codeforlife-design#99]
Independent students don't have access to the teaching material or any introduction to Python.

From Keith Avery:
"Why are there empty brackets after many of the commands? I'm assuming they are nul parameters.
Why do some lines end in a colon? I'm assuming it indicates a multi-line structure.
What about indents? I discovered later that they are not just to improve readability, but are vital to the 
correct running of the program."

**Comment by lauracumming** [comment]
@dionizh this is something we need to think about with Gitbook link for independent students

**Comment by lauracumming** [comment]
They have access now, although it needs tailoring to them
